<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Incorrect username or password.' => 'Λάθος όνομα χρήστη ή κωδικός.',
	'Create Nurse' => 'Δημιουργία Νοσοκόμου',
	'Nurses' => 'Νοσοκόμοι',
	'Create' => 'Δημιουργία',
	'Update' => 'Ενημέρωση',
	'Clinic' => 'Κλινική',
	'Shift' => 'Βάρδια',
	'View' => 'Προβολή',
	'Yes' => 'Ναι',
	'No' => 'Όχι',
	'Delete' => 'Διαγραφή',
	'Error' => 'Σφάλμα',
	'File upload failed.' => 'Η μεταφόρτωση απέτυχε.',
	'Home' => 'Αρχική',
	'ID' => 'Ταυτότητα',
	'CI Name' => ' Όνομα κλινικής',
	'CI Proistamenos' => 'Προϊστάμενος-η Κλινικής',
	'CI Tomearxhs' => 'Τομεάρχης Κλινικής',
	'CI Dieuthunths' => 'Διευθυντής-τρια Κλινικής',
	'CI Phone1' => 'Τηλέφωνο Κλινικής 1',
	'CI Phone2' => 'Τηλέφωνο Kλινικής 2',
	'Description' => 'Περιγραφή',
	'Is Reduced' =>'Μειωμένο Ωράριο;',	
	'Submit' => 'Αποστολή',
	'Thank you for contacting us. We will respond to you as soon as possible.' => 'Ευχαριστούμε για την επικοινωνία. Θα σας απαντήσουμε το γρηγορότερο δυνατό.',
];
